CREATE SCHEMA IF NOT EXISTS parts;

CREATE FOREIGN TABLE IF NOT EXISTS parts.issues_0 PARTITION OF public.issues
FOR VALUES FROM ('1') TO ('500') SERVER shard1;


CREATE FOREIGN TABLE IF NOT EXISTS parts.issues_2 PARTITION OF public.issues
FOR VALUES FROM ('1000') TO ('1500') SERVER shard1;


CREATE FOREIGN TABLE IF NOT EXISTS parts.issues_4 PARTITION OF public.issues
FOR VALUES FROM ('2000') TO ('2500')  SERVER shard1;


CREATE FOREIGN TABLE IF NOT EXISTS parts.issues_6 PARTITION OF public.issues
FOR VALUES FROM ('3000') TO ('3500')  SERVER shard1;

